# Generated by Django 4.2.4 on 2023-09-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='get_categories', to='blog.category', verbose_name='categorias'),
        ),
    ]
